// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjnRCAlJjq6Y69FuhsqDtJLs7t4TR6GI',
    appId: '1:504423796449:web:0133dd7ed43eb21bfc71a0',
    messagingSenderId: '504423796449',
    projectId: 'ieid-8d946',
    authDomain: 'ieid-8d946.firebaseapp.com',
    storageBucket: 'ieid-8d946.appspot.com',
    measurementId: 'G-XPGX4ERB9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLH1CRQE1oIeIjm7KYsTmC52oxhHUYLHk',
    appId: '1:504423796449:android:e7ac91aa147091d2fc71a0',
    messagingSenderId: '504423796449',
    projectId: 'ieid-8d946',
    storageBucket: 'ieid-8d946.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRvbKxk42kh5URuDn7fAMOpOg2RXB2uuw',
    appId: '1:504423796449:ios:8d9a554bd647c724fc71a0',
    messagingSenderId: '504423796449',
    projectId: 'ieid-8d946',
    storageBucket: 'ieid-8d946.appspot.com',
    iosBundleId: 'com.example.ieid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRvbKxk42kh5URuDn7fAMOpOg2RXB2uuw',
    appId: '1:504423796449:ios:40c950e7e669a1d3fc71a0',
    messagingSenderId: '504423796449',
    projectId: 'ieid-8d946',
    storageBucket: 'ieid-8d946.appspot.com',
    iosBundleId: 'com.example.ieid.RunnerTests',
  );
}
